### ISSUE TITLE
modlue not included

### ISSUE THREAD

**Issue by lumpynose** [russhughes/ili9342c_mpy#2]
If I compile micropython with just "make" I get a firmware.bin that works.  But when I use "make USER_C_MODULES=../../../ili9342c_mpy/ all" it works, but it complains about the ili9342c module not being there when I try your examples.  It also complained about the fonts not being there when I tried mono_fonts.py.  The size of the .bin file is exactly the same as when I make it without the USER_C_MODULES and there isn't anything in the build directory for ili9342c.

I tried your firmware.bin file and it went bonkers complaining about partition 3 being invalid; I was using the esptool.py command given on the micropython site.  I then saw what m5stack uses and changed my command to the following and then it worked.  Yay, I got to see the flying toasters!  But I'd like to know why my build isn't "flying".

    esptool.py \
        --chip esp32 \
        --port ${PORT} \
        --baud ${BAUD} \
        --flash_mode dio \
        --flash_freq 80m \
        --flash_size detect \
        write_flash -z 0x1000 \
        ${BIN}

**Comment by russhughes** [comment]
This is probably related to the recent move to a CMake build system. See https://forum.micropython.org/viewtopic.php?f=18&t=9820 for more information.

Once a method of adding external C modules is worked out I will support it.
Until then the driver can be compiled using ESP IDF v4 and the MicroPython 1.14 source from https://micropython.org/resources/source/micropython-1.14.tar.xz or the github source if you use the 1.14 release tag .

You need to copy the fonts you want to use to the device or place them in the modules subdirectory of the ports/esp32 directory if you want them to be frozen in the firmware.

**Comment by lumpynose** [comment]
Great, thanks.  I'm glad you know what's amiss and that there's a solution.

**Comment by lumpynose** [comment]
In any event I don't need to compile it since your .bin works fine.
