### ISSUE TITLE
Inverted screen

### ISSUE THREAD

**Issue by jajito** [russhughes/ili9342c_mpy#3]
Hi, congratulations for your excellent job.
I have installed your ST7789 firmware on my TTGO T-Display and it is marvellous.
I am trying to use your ili9342c firmware with the TTGO T4, and found some issues that I have solved.
The connection of the pins that appears in the TTGO web is not correct.
This one works:
MOSI 23
CLK 18
CS 27
DC 32 (THIS IS WRONG IN THE INFO OF THE MODULE)
RST 5
Backlight Pin 4
(You have to use your library option backlight=Pin(4, Pin.OUT))
Now the screen works, but colours and screen are inverted.
I have used your library option 
tft.inversion_mode(0)
and the colours now are ok.
But the screen is still inverted.
Is there any solution for that?
Thanks in advance, congratulations for your wonderful job and keep on helping us!

```
spi = SPI(
        2,
        baudrate=40000000,
        polarity=1,
        phase=1,
        sck=Pin(18),
        mosi=Pin(23))

    # initialize display

tft = ili9342c.ILI9342C(
        spi,
        240,
        320,
        reset=Pin(5, Pin.OUT),
        cs=Pin(27, Pin.OUT),
        dc=Pin(32, Pin.OUT),
        backlight=Pin(4, Pin.OUT),
        rotation=0
        )
tft.init()
tft.inversion_mode(0)
```

**Comment by russhughes** [comment]
By inverted, do you mean side down or are the colors wrong? If upside down, look at the rotation parameter. If its a color issue can you show me a picture of whats happening?

**Comment by jajito** [comment]
Thanks!. The colours are fixed with inversion_mode(0).
I mean inverted like a mirror.

**Comment by jajito** [comment]
![IMG20210412084821](https://user-images.githubusercontent.com/59225459/114352308-05bd5700-9b6c-11eb-8bc4-d62be2c13ad1.jpg)

**Comment by russhughes** [comment]
This appears to be a difference in how the ili9341 handles memory writing compared to the ili9342c.  Other drivers support 4 additional rotation settings that are also mirrored.  I'll add support for this but I will need to look and see if I have a ili9341 display for testing.

**Comment by jajito** [comment]
Thank you very much!

**Comment by russhughes** [comment]
I uploaded new drivers, try rotation values 4 through 7. I'm not sure they are all correct as I do not have access to a ILI9341 to test.  They appear mirrored on my display so I think they will appear correctly on yours.

**Comment by jajito** [comment]
Now it works, the mirrored option is perfect.
Thanks Russ for your job.

**Comment by russhughes** [comment]
Excellent.

**Comment by aguaviva** [comment]
This works like a charm!
