### ISSUE TITLE
fonts not included inside the firmware for v1.17 

### ISSUE THREAD

**Issue by aguaviva** [russhughes/ili9342c_mpy#4]
I managed to compile v1.17 and it works like a charm :)

 However I wasn't able to include in the firmware the font modules. Why is that? What is the bit that makes the fonts to get frozen into the firmware? I haven't seen any references to that in the firmware. Any pointers on how to fix this are welcome :)

**Comment by russhughes** [comment]
Copy the font .py files you want to include in the firmware as frozen python modules into the modules subdirectory in the micropython/ports/ directory you are working with, then rebuild the firmware. Be aware there is a limit to the flash space available. You will know you have exceeded this limit if you receive an error message saying the code won't fit in the partition or if your firmware continuously reboots with an error.

**Comment by aguaviva** [comment]
Ooooh, that was the trick! Thanks for the quick response :) 

BTW I am currently displaying the BigBuckBunny.jpg in my ili9341and it looks sooooooooooo cute! :)

**Comment by russhughes** [comment]
If you like the jpg, checkout the movie https://github.com/russhughes/TinyBigBuckBunny
